---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: \.json$|\.ipynb$
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer
        exclude: \.ipynb$
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-toml
      - id: check-yaml
      - id: name-tests-test
        args: [--pytest-test-first]
        exclude: ^tests/test_data/|^tests/helpers\.py$
      - id: check-merge-conflict
  - repo: https://github.com/jsh9/muff-pre-commit
    rev: 0.13.2
    hooks:
      - id: muff-format
        args: [--config, muff.toml]
  - repo: https://github.com/jsh9/blank-line-after-blocks
    rev: 0.1.4
    hooks:
      - id: blank-line-after-blocks
      - id: blank-line-after-blocks-jupyter
  - repo: https://github.com/lyz-code/yamlfix
    rev: 1.18.0
    hooks:
      - id: yamlfix
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.2
    hooks:
      - id: toml-sort-fix
        args:
          - --in-place
          - --sort-table-keys
          - --sort-inline-tables
          - --sort-first=name,version,dependencies,requires-python,authors,maintainers
          - --trailing-comma-inline-array
          - --sort-inline-arrays
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.15.0
    hooks:
      - id: pretty-format-ini
        args: [--autofix]
  - repo: https://github.com/hukkin/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        args: [--wrap, '79', --number]
        additional_dependencies: [mdformat-gfm]
        exclude: ^tests/test_data/
  - repo: https://github.com/jsh9/format-json
    rev: 0.1.2
    hooks:
      - id: format-json
        args:
          - --autofix
          - --no-ensure-ascii
          - --indent=4
          - --no-sort-keys
          - --no-eof-newline
  - repo: https://github.com/jsh9/markdown-heading-numbering
    rev: 0.1.0
    hooks:
      - id: markdown-heading-numbering
        exclude: ^CHANGELOG\.md$|^tests/test_data/
  - repo: local
    hooks:
      - id: markdown-toc-creator
        name: Format self (markdown table of contents)
        entry: python
        args: [-m, markdown_toc_creator.main]
        language: python
        types: [markdown]
        exclude: ^tests/test_data|^CHANGELOG\.md$|^AGENTS\.md$
        additional_dependencies:
          - click>=8.0.0
          - beautifulsoup4>=4.12.0
          - click-config-file-injection-utils>=0.1.0
          - tomli>=2.0.0
  - repo: https://github.com/jsh9/format-docstring
    rev: 0.2.2
    hooks:
      - id: format-docstring
        name: Format docstrings in .py files
        args: [--line-length=79]
      - id: format-docstring-jupyter
        name: Format docstrings in .ipynb files
        args: [--line-length=79]
